// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB95z8ADezwSAzNbPqXfCe9N8hWJcjvFwU',
    appId: '1:702688765942:web:9950786cc72dfea1ff89d7',
    messagingSenderId: '702688765942',
    projectId: 'deliveryfood-53814',
    authDomain: 'deliveryfood-53814.firebaseapp.com',
    storageBucket: 'deliveryfood-53814.appspot.com',
    measurementId: 'G-VY2F8HZD0N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA28eZBkQXyhkSeDAMgU1mqq010aduX6VM',
    appId: '1:702688765942:android:25f7cad64a70d627ff89d7',
    messagingSenderId: '702688765942',
    projectId: 'deliveryfood-53814',
    storageBucket: 'deliveryfood-53814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs2IHvQstBnIhvDJHsHV2lNY4hENqi6eg',
    appId: '1:702688765942:ios:31cd6d23038212c3ff89d7',
    messagingSenderId: '702688765942',
    projectId: 'deliveryfood-53814',
    storageBucket: 'deliveryfood-53814.appspot.com',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs2IHvQstBnIhvDJHsHV2lNY4hENqi6eg',
    appId: '1:702688765942:ios:31cd6d23038212c3ff89d7',
    messagingSenderId: '702688765942',
    projectId: 'deliveryfood-53814',
    storageBucket: 'deliveryfood-53814.appspot.com',
    iosBundleId: 'com.example.deliveryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB95z8ADezwSAzNbPqXfCe9N8hWJcjvFwU',
    appId: '1:702688765942:web:e7d2b84e74062793ff89d7',
    messagingSenderId: '702688765942',
    projectId: 'deliveryfood-53814',
    authDomain: 'deliveryfood-53814.firebaseapp.com',
    storageBucket: 'deliveryfood-53814.appspot.com',
    measurementId: 'G-JT6C5XFR0B',
  );

}